#!/bin/sh

set -e

case "$1" in
    configure)

	# Add system daemon user
	addgroup --system authenticator
	adduser --system --home /var/lib/authenticator \
		--disabled-password --ingroup authenticator authenticator
	adduser authenticator gpio

	# Add local cache file
	if [ ! -d "/var/cache/authenticator" ]; then
	    mkdir /var/cache/authenticator
	fi
	chown authenticator:authenticator /var/cache/authenticator

	if [ ! -f /var/cache/authenticator/patron.db ]; then
	   touch /var/cache/authenticator/patron.db
	fi
	chown authenticator:authenticator /var/cache/authenticator/patron.db
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
	;;
    
    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
