#!/bin/sh

set -e

case "$1" in
    purge)
	if [ -x "$(command -v deluser)" ]; then
	    deluser --quiet --system authenticator > /dev/null || true
	else
	    echo >&2 "not removing authenticator system account because deluser command was not found"
	fi

	# Delete directory for local cache file
	if [ -d "/var/cache/authenticator" ]; then
	    rm -rf "/var/cache/authenticator"
	fi
	;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
