#!/usr/bin/perl

# Copyright 2022 Hypernova Oy
#

use Modern::Perl;
use Carp;
use Data::Printer;
use Getopt::Long qw(:config no_ignore_case);

use SSAuthenticator;
use SSAuthenticator::Config;
use SSAuthenticator::Mailbox;
use SSAuthenticator::OpeningHours;
use SSAuthenticator::Transaction;
use SSAuthenticator::Util;

my ($help, $message, $verbose, $barcodeReader, $apiTest, $getConfig, $setConfig, $askpin);
my @params;

GetOptions(
    'h|help'                      => \$help,
    'v|verbose=i'                 => \$verbose,
    'm|message=s'                 => \$message,
    'p|params=s'                  => \@params,
    'b'                           => \$barcodeReader,
    'a|api=s'                     => \$apiTest,
    'askpin=s'                    => \$askpin,
    'c|config=s'                  => \$setConfig,
    'get-config'                  => \$getConfig,
);

$ENV{SSA_LOG_LEVEL} = $verbose if $verbose;

my $usage = <<USAGE;

SSSync - Synchronize stuff from Koha to Toveri

Currently only opening hour information.
This script needs to be crontabbed hourly, to poll Koha for changes.

Persists polled data on disk for SSAuthenticator to use.

Parameters

  -h --help               HELP!
  -v --verbose            Int, sets the verbosity level:
                            -1 less verbose
                            2  most verbose
  -c --config /path/conf  Load SSAuthenticator configuration from the given file

Environment variables

  SSSAUTHENTICATOR_CONFIG Same as setting the --config -parameter

EXAMPLES

    #Checks Koha for the new opening hours.
    sssync

USAGE

if ($help) {
  print $usage;
  exit 0;
}

if ($setConfig) {
  SSAuthenticator::Config::setConfigFile($setConfig);
  SSAuthenticator::Config::getConfig(); # Make sure the config is loaded before logging or anything else is initialized
}

SSAuthenticator::OpeningHours::synchronize();
